export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";
export const DELETE_MEMBER_SUCCESS = "DELETE_MEMBER_SUCCESS";
export const VIEW_MEMBER_SUCCESS = "VIEW_MEMBER_SUCCESS";
export const GET_ALL_MEMBER_SUCCESS = "GET_ALL_MEMBER_SUCCESS";
export const ASSOCIATE_MEMBER_SUCCESS = "ASSOCIATE_MEMBER_SUCCESS";